# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [203]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [204]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [205]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn import datasets

### Set random seed

In [206]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [207]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [208]:
type(iris)

sklearn.utils.Bunch

In [209]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [210]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [211]:
X=iris.data
y=iris.target

In [212]:
print("Shape of iris dataset X and y are:", X.shape, y.shape)

Shape of iris dataset X and y are: (150, 4) (150,)


In [213]:
print(X[0,:])
print(np.unique(y))

[5.1 3.5 1.4 0.2]
[0 1 2]


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [214]:
#split train and test data into 70:30 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=15)

In [215]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [216]:
print(np.unique(y_train))
print(np.unique(y_test))

[0 1 2]
[0 1 2]


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [217]:
#One hot encoding
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

In [218]:
print(y_train)
print(y_test)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

## Question 5

### Initialize a sequential model
- Define a sequential model

In [219]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#another way of defining a sequential
#model = tf.keras.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [220]:
#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(3, input_shape=(4,), activation='softmax'))
#4 inputs + 1 bias  w=1 and b=1. so applying in y=wx+b ==> y=1x4+1 =5. Since there are 3 output in target, it would be 5*3=15 params.

In [221]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [222]:
#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [223]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [224]:
model.fit(X_train, y_train,
          validation_data=(X_test, y_test), 
          epochs=100,
          #batch_size=32)
          batch_size=X_train.shape[0])

Epoch 1/100
1/1 [==============================] - 0s 477ms/step - loss: 3.1866 - accuracy: 0.3393 - val_loss: 2.7569 - val_accuracy: 0.3158
Epoch 2/100
1/1 [==============================] - 0s 42ms/step - loss: 2.7595 - accuracy: 0.3393 - val_loss: 2.3638 - val_accuracy: 0.3158
Epoch 3/100
1/1 [==============================] - 0s 44ms/step - loss: 2.3795 - accuracy: 0.3393 - val_loss: 2.0362 - val_accuracy: 0.3158
Epoch 4/100
1/1 [==============================] - 0s 39ms/step - loss: 2.0646 - accuracy: 0.3393 - val_loss: 1.7848 - val_accuracy: 0.3158
Epoch 5/100
1/1 [==============================] - 0s 42ms/step - loss: 1.8244 - accuracy: 0.3393 - val_loss: 1.6049 - val_accuracy: 0.3158
Epoch 6/100
1/1 [==============================] - 0s 42ms/step - loss: 1.6532 - accuracy: 0.3393 - val_loss: 1.4800 - val_accuracy: 0.3158
Epoch 7/100
1/1 [==============================] - 0s 46ms/step - loss: 1.5340 - accuracy: 0.3125 - val_loss: 1.3926 - val_accuracy: 0.3158
Epoch 8/100
1/1 [==

## Question 10

### Make predictions
- Predict labels on one row

In [225]:
input_data = np.expand_dims(X_test[0], axis=0)
input_data.shape

(1, 4)

In [226]:
pred = model.predict(input_data)


In [227]:
pred[0]

array([0.60213184, 0.06256179, 0.33530638], dtype=float32)

In [228]:
pred.shape

(1, 3)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [229]:
y_test[0]

array([1., 0., 0.], dtype=float32)

By comparing the actual label with the prediction, the class 0 has highest % value of 87% and the model predicted correctly as 1 - which is class 0.



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [230]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [231]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [232]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [254]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [234]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [235]:
df_prices=pd.read_csv('prices.csv',error_bad_lines=False, encoding="latin-1")

In [236]:
df_prices.head()

,date,symbol,open,close,low,high,volume
0,2016-01-05 00:00:00,WLTW,123.430000,125.839996,122.309998,126.250000,2163600.0
1,2016-01-06 00:00:00,WLTW,125.239998,119.980003,119.940002,125.540001,2386400.0
2,2016-01-07 00:00:00,WLTW,116.379997,114.949997,114.930000,119.739998,2489500.0
3,2016-01-08 00:00:00,WLTW,115.480003,116.620003,113.500000,117.440002,2006300.0
4,2016-01-11 00:00:00,WLTW,117.010002,114.970001,114.089996,117.330002,1408600.0


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [237]:
df_prices.drop(['date','symbol'], axis=1, inplace=True)

In [238]:
df_prices.head()

,open,close,low,high,volume
0,123.430000,125.839996,122.309998,126.250000,2163600.0
1,125.239998,119.980003,119.940002,125.540001,2386400.0
2,116.379997,114.949997,114.930000,119.739998,2489500.0
3,115.480003,116.620003,113.500000,117.440002,2006300.0
4,117.010002,114.970001,114.089996,117.330002,1408600.0


In [239]:
print("shape of price dataset:", df_prices.shape)

shape of price dataset: (851264, 5)


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [240]:
df_prices_final=df_prices.iloc[:1000]

#another easy way--
#df_prices_final=df_prices.head(1000)

In [241]:
df_prices_final.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [242]:
X=df_prices_final.iloc[:,0:4]
Y=df_prices_final.iloc[:, 4:5]/1000000

In [243]:
X.head()

,open,close,low,high
0,123.430000,125.839996,122.309998,126.250000
1,125.239998,119.980003,119.940002,125.540001
2,116.379997,114.949997,114.930000,119.739998
3,115.480003,116.620003,113.500000,117.440002
4,117.010002,114.970001,114.089996,117.330002


In [244]:
Y.head()

,volume
0,2.1636
1,2.3864
2,2.4895
3,2.0063
4,1.4086


## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [245]:
X=np.asarray(X, dtype='float32')
Y=np.asarray(Y, dtype='float32')

#Another method
#X=np.array(X).astype('float32')
#Y=np.array(Y).astype('float32')

In [ ]:
type(X), type(Y)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [246]:
X=tf.math.l2_normalize(X)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [247]:
#We are initializing weights and Bias with Zero
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [248]:
@tf.function
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    yb = tf.add(xw_matmul, b)
    
    return yb

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [249]:
@tf.function
def loss(y_actual, y_predicted):   #rmse = (y-ybar)^2/n
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [250]:
@tf.function
def train(X, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(X, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [251]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(X, Y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, loss(Y, prediction(X, w, b)).numpy())    


Current Loss on iteration 0 236.16805
Current Loss on iteration 1 235.09369
Current Loss on iteration 2 234.06194
Current Loss on iteration 3 233.07103
Current Loss on iteration 4 232.11937
Current Loss on iteration 5 231.20546
Current Loss on iteration 6 230.32774
Current Loss on iteration 7 229.4848
Current Loss on iteration 8 228.67522
Current Loss on iteration 9 227.89775
Current Loss on iteration 10 227.15106
Current Loss on iteration 11 226.43399
Current Loss on iteration 12 225.7453
Current Loss on iteration 13 225.08392
Current Loss on iteration 14 224.44872
Current Loss on iteration 15 223.83868
Current Loss on iteration 16 223.25284
Current Loss on iteration 17 222.69019
Current Loss on iteration 18 222.14981
Current Loss on iteration 19 221.6309
Current Loss on iteration 20 221.1325
Current Loss on iteration 21 220.65384
Current Loss on iteration 22 220.19417
Current Loss on iteration 23 219.75272
Current Loss on iteration 24 219.32877
Current Loss on iteration 25 218.92157


### Observe values of Weight
- Print the updated values

In [252]:
#Check Weights and Bias
print('Weights:\n', w.numpy())


Weights:
 [[0.0194333 ]
 [0.01969694]
 [0.01937149]
 [0.01976266]]


### Observe values of Bias
- Print the updated values

In [253]:
print('Bias:\n',b.numpy())

Bias:
 [4.608607]
